//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data.xml.
        /// </summary>
        internal static string CACHE_XML_FILE {
            get {
                return ResourceManager.GetString("CACHE_XML_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данному файлу не присвоена программа для запуска.
        /// </summary>
        internal static string CANNOT_OPEN_FILE {
            get {
                return ResourceManager.GetString("CANNOT_OPEN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDOC.
        /// </summary>
        internal static string CLIENT_NAME {
            get {
                return ResourceManager.GetString("CLIENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \EDOC\Files.
        /// </summary>
        internal static string DOWNLOADS_FOLDER {
            get {
                return ResourceManager.GetString("DOWNLOADS_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл с таким именем уже существует: .
        /// </summary>
        internal static string FILE_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("FILE_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название не должно содержать символы [\~#%&amp;*{}/:&lt;&gt;?|\&quot;]..
        /// </summary>
        internal static string INVALID_INPUT {
            get {
                return ResourceManager.GetString("INVALID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon NewEventTray {
            get {
                object obj = ResourceManager.GetObject("NewEventTray", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string PERMISSIBLE_DATE_RANGE_IN_DAYS {
            get {
                return ResourceManager.GetString("PERMISSIBLE_DATE_RANGE_IN_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер недоступен.
        /// </summary>
        internal static string SERVER_NOT_FOUND {
            get {
                return ResourceManager.GetString("SERVER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автономная работа.
        /// </summary>
        internal static string SERVER_OFFLINE {
            get {
                return ResourceManager.GetString("SERVER_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер доступен.
        /// </summary>
        internal static string SERVER_ONLINE {
            get {
                return ResourceManager.GetString("SERVER_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ServerOfflineTray {
            get {
                object obj = ResourceManager.GetObject("ServerOfflineTray", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDOC_LINK.
        /// </summary>
        internal static string STARTUP_LINK_NAME {
            get {
                return ResourceManager.GetString("STARTUP_LINK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDEVENT_APPROVE_BOX.
        /// </summary>
        internal static string TAG_ADDEVENT_APPROVE_BOX {
            get {
                return ResourceManager.GetString("TAG_ADDEVENT_APPROVE_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMANDER_PATH.
        /// </summary>
        internal static string TAG_COMMANDER_PATH {
            get {
                return ResourceManager.GetString("TAG_COMMANDER_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIDE_ALLOWANCE.
        /// </summary>
        internal static string TAG_HIDE_ALLOWANCE {
            get {
                return ResourceManager.GetString("TAG_HIDE_ALLOWANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIDE_CLOSED.
        /// </summary>
        internal static string TAG_HIDE_CLOSED {
            get {
                return ResourceManager.GetString("TAG_HIDE_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPEN_FILE_LOCATION.
        /// </summary>
        internal static string TAG_OPEN_FILE_LOCATION {
            get {
                return ResourceManager.GetString("TAG_OPEN_FILE_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTK_STATUS.
        /// </summary>
        internal static string TAG_OTK_STATUS {
            get {
                return ResourceManager.GetString("TAG_OTK_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SORT_DIR.
        /// </summary>
        internal static string TAG_SORT_DIR {
            get {
                return ResourceManager.GetString("TAG_SORT_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SORT_NAME.
        /// </summary>
        internal static string TAG_SORT_NAME {
            get {
                return ResourceManager.GetString("TAG_SORT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOUND_EVENT.
        /// </summary>
        internal static string TAG_SOUND_EVENT {
            get {
                return ResourceManager.GetString("TAG_SOUND_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOUND_STATUS.
        /// </summary>
        internal static string TAG_SOUND_STATUS {
            get {
                return ResourceManager.GetString("TAG_SOUND_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STARTUP_TRAY.
        /// </summary>
        internal static string TAG_STARTUP_TRAY {
            get {
                return ResourceManager.GetString("TAG_STARTUP_TRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOCK_STATUS.
        /// </summary>
        internal static string TAG_STOCK_STATUS {
            get {
                return ResourceManager.GetString("TAG_STOCK_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TASKBAR_INDICATION_STATUS.
        /// </summary>
        internal static string TAG_TASKBAR_INDICATION_STATUS {
            get {
                return ResourceManager.GetString("TAG_TASKBAR_INDICATION_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRAY_INDICATION_STATUS.
        /// </summary>
        internal static string TAG_TRAY_INDICATION_STATUS {
            get {
                return ResourceManager.GetString("TAG_TRAY_INDICATION_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TURNOUT_EVENT.
        /// </summary>
        internal static string TAG_TURNOUT_EVENT {
            get {
                return ResourceManager.GetString("TAG_TURNOUT_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TURNOUT_STATUS.
        /// </summary>
        internal static string TAG_TURNOUT_STATUS {
            get {
                return ResourceManager.GetString("TAG_TURNOUT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE_COMMANDER.
        /// </summary>
        internal static string TAG_USE_COMMANDER {
            get {
                return ResourceManager.GetString("TAG_USE_COMMANDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный логин/пароль.
        /// </summary>
        internal static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
    }
}
